version: "3.1"

services:
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    networks:
      - postgres
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://localhost:5432/sonar
      SONAR_JDBC_USERNAME: pacifique
      SONAR_JDBC_PASSWORD: pacifique
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: pacifique
      POSTGRES_PASSWORD: pacifique
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  cache:
    container_name: app-cache
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=password123
      - REDIS_AOF_ENABLED=no
      - REDIS_PORT_NUMBER=6379
    networks:
      - postgres
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 500mb
    volumes:
      - cache:/data

networks:
  postgres:
    driver: bridge
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres:
  pgadmin:
  cache:
