version: "3.1"

services:
  web-api:
    build:
      context: .
    container_name: taskmanagement-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url":"jdbc:postgresql://postgres:5432/task-management-db?useSSL=false",
             "spring.datasource.username":"pacifique",
             "spring.datasource.password":"pacifique",
             "spring.datasource.driver-class-name": "org.postgresql.Driver",
             "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
             "spring.jpa.hibernate.ddl-auto":"none"
           }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  postgres:
    container_name: task-management-db
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "pacifique" ]
      interval: 10s
      timeout: 5s
      retries: 3

    environment:
      POSTGRES_USER: pacifique
      POSTGRES_PASSWORD: pacifique
      POSTGRES_DB: task-management-db
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - sonarqube_db:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
      container_name: task-management-pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@gmail.com}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - pgadmin:/var/pgadmin
      ports:
        - "5050:80"
      networks:
        - postgres
      restart: unless-stopped
  cache:
      container_name: task-management-cache
      image: bitnami/redis:latest
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_PASSWORD=password123
        - REDIS_AOF_ENABLED=no
        - REDIS_PORT_NUMBER=6379
      networks:
        - postgres
      restart: unless-stopped
      ports:
        - "6379:6379"
      command: /opt/bitnami/scripts/redis/run.sh --maxmemory 500mb
      volumes:
        - cache:/data

networks:
    postgres:
      driver: bridge
volumes:
    postgresql_data:
    pgadmin:
    cache:
    sonarqube_db: