server:
  port: 8080
spring:
  profiles:
    active: dev

---
spring:
  data:
    redis:
      port: 6379
      password: password123
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/todoapp
    username: pacifique
    password: pacifique
    driver-class-name: org.postgresql.Driver
    generate-unique-name: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: dev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todotest
    username: pacifique
    password: pacifique
    driver-class-name: org.postgresql.Driver
    generate-unique-name: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  config:
    activate:
      on-profile: test