server:
  port: 8080
spring:
  profiles:
    active: dev
  main:
    log-startup-info: true
sendgrid:
    api-key: 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

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha


application:
  security:
    jwt:
      secret-key: springbootbackendapplicationsecretkeyspringbootbackendapplicationsecretkey
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

---
spring:
  data:
    redis:
      port: 6379
      password: password123
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/task-management-db
    username: pacifique
    password: pacifique
    driver-class-name: org.postgresql.Driver
    generate-unique-name: true
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
  config:
    activate:
      on-profile: dev


---
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  config:
    activate:
      on-profile: test