server:
  port: 8080
spring:
  profiles:
    active: dev

---
spring:
  data:
    redis:
      port: 6379
      password: password123
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/todoapp
    username: pacifique
    password: pacifique
    driver-class-name: org.postgresql.Driver
    generate-unique-name: true
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  config:
    activate:
      on-profile: dev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method