server:
  port: 8080
spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: pacifiquetwagirayesu@gmail.com
    password: "ivarqhricvrojijw"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

---
spring:
  data:
    redis:
      port: 6379
      password: password123
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/task-management-db
    username: pacifique
    password: pacifique
    driver-class-name: org.postgresql.Driver
    generate-unique-name: true
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  config:
    activate:
      on-profile: dev

---
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  config:
    activate:
      on-profile: test